//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18052
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ukadc.Diagnostics {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ukadc.Diagnostics.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is invalid to specify both a propertyToken (&apos;{0}&apos;) and a dataProperty element on a &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string BothPropertyTokenAndDataPropertyDefined {
            get {
                return ResourceManager.GetString("BothPropertyTokenAndDataPropertyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cleanInterval attribute must be a valid TimeSpan greater than Zero. The value &apos;{0}&apos; is invalid. Using default cleanInterval &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string CleanIntervalCannotBeZero {
            get {
                return ResourceManager.GetString("CleanIntervalCannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cleanInterval attribute must be a valid TimeSpan. The value &apos;{0}&apos; is invalid. Using default cleanInterval &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string CleanIntervalInvalid {
            get {
                return ResourceManager.GetString("CleanIntervalInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not create instance of type &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string CouldNotCreateInstanceOfType {
            get {
                return ResourceManager.GetString("CouldNotCreateInstanceOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A default constructor could not be found on type &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string CouldNotFindEmptyConstructor {
            get {
                return ResourceManager.GetString("CouldNotFindEmptyConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The property &apos;{0}&apos; is of type &apos;{1}&apos; which does not implement IComparable or IConvertible and therefore cannot be evaluated or compared against. ähnelt.
        /// </summary>
        internal static string DoesNotImplementRightInterfaces {
            get {
                return ResourceManager.GetString("DoesNotImplementRightInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Type &apos;{0}&apos; does not inherit from &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string InheritanceError {
            get {
                return ResourceManager.GetString("InheritanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MultiFilter configuration error: No filterGroup with the name &apos;{0}&apos; could be found. ähnelt.
        /// </summary>
        internal static string MultiFilterGroupError {
            get {
                return ResourceManager.GetString("MultiFilterGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MultiFilter configuration error: filterGroup must contain at least 1 or more filters. ähnelt.
        /// </summary>
        internal static string MultiFilterMustContainOneFilter {
            get {
                return ResourceManager.GetString("MultiFilterMustContainOneFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No &apos;{0}&apos; configuration section was found (&lt;section name=&apos;{0}&apos; type=&apos;{1}&apos; /&gt;). ähnelt.
        /// </summary>
        internal static string NoConfigurationSectionFound {
            get {
                return ResourceManager.GetString("NoConfigurationSectionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All single parameter constructors on the type &apos;{0}&apos; were tried but none could use the parameter &apos;{1}&apos; passed in. ähnelt.
        /// </summary>
        internal static string NoConstructorFound {
            get {
                return ResourceManager.GetString("NoConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot find a field or property called {0} on type {1} or it cannot be read ähnelt.
        /// </summary>
        internal static string NoPropOrFieldOrInaccessible {
            get {
                return ResourceManager.GetString("NoPropOrFieldOrInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FastPropertyGetter: There is no readable property &apos;{0}&apos; on type &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string NoReadableProperty {
            get {
                return ResourceManager.GetString("NoReadableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Type &apos;{0}&apos; does not inherit or derive from the &apos;{1}&apos; type. ähnelt.
        /// </summary>
        internal static string NotAssignableFrom {
            get {
                return ResourceManager.GetString("NotAssignableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Operation &apos;{0}&apos; is not supported by the &apos;{1}&apos;. Try one of the following operations &apos;{2}&apos;. ähnelt.
        /// </summary>
        internal static string OperationNotSupported {
            get {
                return ResourceManager.GetString("OperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PropertyFilter configuration error: No propertyFilter with the name &apos;{0}&apos; could be found. ähnelt.
        /// </summary>
        internal static string PropertyFilterNotFound {
            get {
                return ResourceManager.GetString("PropertyFilterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SmtpTraceListener configuration error: No section with the name &apos;{0}&apos; could be found. ähnelt.
        /// </summary>
        internal static string SmtpTraceListenerConfigError {
            get {
                return ResourceManager.GetString("SmtpTraceListenerConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SqlTraceListener configuration error: No section with the name &apos;{0}&apos; could be found. ähnelt.
        /// </summary>
        internal static string SqlTraceListenerConfigError {
            get {
                return ResourceManager.GetString("SqlTraceListenerConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The token &apos;{0}&apos; already exists in the token dictionary and cannot be added. ähnelt.
        /// </summary>
        internal static string TokenAlreadyExists {
            get {
                return ResourceManager.GetString("TokenAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can only specify one of format, type and dynamicProperty on a token element (token name=&apos;{0}&apos;). ähnelt.
        /// </summary>
        internal static string TokenElementIncorrect {
            get {
                return ResourceManager.GetString("TokenElementIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type &apos;{0}&apos; has already been registered with the locator. ähnelt.
        /// </summary>
        internal static string TypeAlreadyRegistered {
            get {
                return ResourceManager.GetString("TypeAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Type &apos;{0}&apos; does not implement IComparable and cannot be used by the &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string TypeDoesNotImplementIComparable {
            get {
                return ResourceManager.GetString("TypeDoesNotImplementIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type &apos;{0}&apos; has not been registered with this locator. ähnelt.
        /// </summary>
        internal static string TypeNotRegistered {
            get {
                return ResourceManager.GetString("TypeNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The token &apos;{0}&apos; does not exist in the token dictionary. ähnelt.
        /// </summary>
        internal static string UnrecognizedToken {
            get {
                return ResourceManager.GetString("UnrecognizedToken", resourceCulture);
            }
        }
    }
}
